/* Real V3 interaction QA; requires local V3 :8083 and exact V2 :8082 servers.
   No external traffic or real inquiries. Captures only 390/1440 EN/ES; tests all six widths.
   EXIF_V3_ORIGIN / EXIF_V2_ORIGIN / EXIF_V3_ARTIFACT_DIR can override defaults. */
const{chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const origin=process.env.EXIF_V3_ORIGIN||'http://127.0.0.1:8083',baseline=process.env.EXIF_V2_ORIGIN||'http://127.0.0.1:8082';
const output=process.env.EXIF_V3_ARTIFACT_DIR||path.resolve(__dirname,'../docs/review-v3');fs.mkdirSync(output,{recursive:true});
let assertions=0;const passed=[],metrics=[],captures=[];
function verify(v,m){assert(v,m);assertions++;}
async function copy(page,lang){const wrong=await page.locator('[data-en][data-es]').evaluateAll((es,lang)=>es.filter(e=>e.textContent.trim()!==e.getAttribute('data-'+lang).trim()).map(e=>e.textContent.slice(0,50)),lang);verify(!wrong.length,'Bilingual text mismatch '+wrong.join(' / '));}
async function fit(page){verify(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Horizontal document overflow');const over=await page.locator('main h1, main h2, .v3-folio-index [data-folio], .v3-specimen-controls, .v2-field').evaluateAll(es=>es.filter(e=>{const r=e.getBoundingClientRect();return r.width>0&&(r.left<-1||r.right>innerWidth+1)}).map(e=>e.textContent.slice(0,45)));verify(!over.length,'Content overflow '+over.join('/'));}
async function screenshot(page,version,width,lang,name,full=false){if(![390,1440].includes(width))return;const dir=path.join(output,'images',version);fs.mkdirSync(dir,{recursive:true});if(full)await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await page.waitForTimeout(400);const rel=`images/${version}/${width}-${lang}-${name}.jpg`;await page.screenshot({path:path.join(output,rel),type:'jpeg',quality:80,fullPage:full});captures.push(rel);}
async function context(browser,width,lang,extra={}){const c=await browser.newContext({viewport:{width,height:900},hasTouch:width<860,...extra});await c.route('https://**/*',r=>r.abort());await c.addInitScript(lang=>{localStorage.setItem('exif-language',lang);sessionStorage.setItem('exif-intro-seen','1');window.qaCLS=0;window.qaShifts=[];if('PerformanceObserver' in window){new PerformanceObserver(list=>list.getEntries().forEach(e=>{if(!e.hadRecentInput){qaCLS+=e.value;qaShifts.push(e.value)}})).observe({type:'layout-shift',buffered:true});}},lang);return c;}
(async()=>{const browser=await chromium.launch({executablePath:process.env.EXIF_CHROMIUM_PATH||'/usr/bin/chromium',args:['--no-sandbox']});try{
for(const width of [360,390,768,860,1024,1440])for(const lang of ['en','es']){
 const c=await context(browser,width,lang),p=await c.newPage(),errors=[],missing=[];p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.url().startsWith(origin)&&r.status()>=400)missing.push(r.url())});
 await p.goto(origin+'/expertise');await p.waitForTimeout(450);await fit(p);await copy(p,lang);
 verify(await p.locator('[role="tab"]').count()===3,'Service tabs absent');verify(await p.locator('[role="tabpanel"]:visible').count()===1,'Multiple visible service panels');
 await p.locator('#reading-line').focus();await p.keyboard.press('End');verify((await p.locator('#reading-line').inputValue())==='100','Reading line keyboard control failed');verify((await p.locator('#reading-line').getAttribute('aria-valuetext')).includes(lang==='en'?'guest':'huésped'),'Reading-line accessible value wrong');await screenshot(p,'after',width,lang,'expertise-observe',true);
 await p.locator('#folio-tab-0').focus();await p.keyboard.press('ArrowDown');verify(await p.locator('#folio-tab-1').evaluate(e=>e===document.activeElement),'Service keyboard focus failed');verify(await p.locator('#service-0').isHidden(),'Previous panel remains accessible');await p.locator('[data-emphasis-choice="2"]').click();verify(await p.locator('.v3-direction').getAttribute('data-emphasis')==='2','Priority choice failed');await fit(p);await screenshot(p,'after',width,lang,'expertise-direct',true);
 await p.locator('#folio-tab-1').focus();await p.keyboard.press('End');verify(await p.locator('#folio-tab-2').getAttribute('aria-selected')==='true','End selection failed');await p.locator('[data-format-choice="2"]').click();verify((await p.locator('#format-note').textContent()).includes(lang==='en'?'page':'página'),'Format choice not explained');await fit(p);await copy(p,lang);await screenshot(p,'after',width,lang,'expertise-produce',true);
 await p.locator('.site-header .lang-toggle').click();await copy(p,lang==='en'?'es':'en');verify(await p.locator('#service-2').isVisible(),'Language switch lost service choice');await p.locator('.site-header .lang-toggle').click();
 metrics.push({width,lang,page:'expertise',cls:await p.evaluate(()=>qaCLS),localTransferBytes:await p.evaluate(()=>performance.getEntriesByType('resource').filter(e=>e.name.startsWith(location.origin)).reduce((n,e)=>n+e.transferSize,0))});
 await p.goto(origin+'/approach');await p.waitForTimeout(250);await fit(p);await copy(p,lang);verify(await p.locator('.v3-process-index a').count()===5,'Five process anchors missing');
 await p.locator('[data-process-link="2"]').click();await p.waitForTimeout(800);verify(await p.locator('[data-process-link="2"]').getAttribute('aria-current')==='step','Process index not following reading');await p.locator('#process-2 summary').focus();await p.keyboard.press('Enter');verify(await p.locator('#process-2 details').evaluate(e=>e.open),'Native working-note disclosure failed');await screenshot(p,'after',width,lang,'approach-working-note');
 await p.evaluate(()=>scrollTo(0,0));await screenshot(p,'after',width,lang,'approach',true);
 await p.goto(origin+'/studio');await fit(p);await copy(p,lang);await screenshot(p,'after',width,lang,'studio',true);await p.locator('.v3-letter-anchor').click();await p.waitForTimeout(700);verify(await p.locator('.founder-letter').isVisible(),'Founder letter not reachable');
 await p.goto(origin+'/');await p.waitForFunction(()=>document.body.classList.contains('exif-header-ready'));await p.waitForTimeout(1400);await fit(p);await screenshot(p,'after',width,lang,'hero');await p.locator('.v2-introduction').first().scrollIntoViewIfNeeded();await screenshot(p,'after',width,lang,'positioning');await p.locator('.v3-study').scrollIntoViewIfNeeded();await screenshot(p,'after',width,lang,'study-observe');
 const beforeY=await p.evaluate(()=>scrollY);await p.locator('[data-study-choice="2"]').click();verify(await p.locator('[data-study-panel="2"]').isVisible(),'Study selection failed');verify(await p.locator('[data-study-panel="0"]').isHidden(),'Inactive study reading exposed');await fit(p);await copy(p,lang);await screenshot(p,'after',width,lang,'study-decide');verify(Math.abs(await p.evaluate(()=>scrollY)-beforeY)<100,'Study choice unexpectedly scrolls page');
 await p.locator('.nav-toggle').click();await p.waitForTimeout(850);const link=p.locator('.v1-nav-link[data-route="expertise"]');await link.focus();await p.waitForTimeout(450);verify((await link.locator('.v1-nav-label').textContent())===(lang==='en'?'WHAT WE DO':'QUÉ HACEMOS'),'Hover/focus replaced route landmark');await screenshot(p,'after',width,lang,'drawer');await p.keyboard.press('Escape');await p.waitForTimeout(800);
 await p.goto(origin+'/inquire');await fit(p);await copy(p,lang);await screenshot(p,'after',width,lang,'inquiry',true);let calls=0;await c.route('https://formspree.io/**',r=>{calls++;return r.fulfill({status:200,contentType:'application/json',body:'{}'})});
 for(const [id,val]of [['inquiry-name','Review Guest'],['inquiry-email','guest@example.com'],['inquiry-property','Review property']])await p.locator('#'+id).fill(val);await p.locator('#inquiry-role').selectOption('owner');await p.locator('#inquiry-context').selectOption('opening');verify((await p.locator('.v3-form-readiness').textContent()).includes(lang==='en'?'Ready':'lista'),'Letter readiness missing');await p.locator('#discovery-inquiry button').click();await p.locator('#inquiry-received').waitFor({state:'visible'});verify(calls===1,'Inquiry request duplicated');verify(await p.locator('#inquiry-received').evaluate(e=>e===document.activeElement),'Receipt focus lost');verify((await p.locator('#inquiry-received').textContent()).includes(lang==='en'?'available times':'horarios disponibles'),'Receipt falsely books meeting');await screenshot(p,'after',width,lang,'inquiry-receipt',true);
 verify(!errors.length,'Console/page errors '+errors.join('/'));verify(!missing.length,'Missing local assets '+missing.join('/'));passed.push(`${width}px ${lang}: services/range/priority/format, process/disclosure, studio, study, stable drawer, inquiry, copy and overflow`);console.log('PASS '+passed.at(-1));await c.close();
 if([390,1440].includes(width)){const bc=await context(browser,width,lang),bp=await bc.newPage();for(const [route,name,selector]of [['/','hero',null],['/','positioning','.v2-introduction'],['/','study','.v2-practice'],['/expertise','expertise',null],['/approach','approach',null],['/studio','studio',null],['/inquire','inquiry',null]]){await bp.goto(baseline+route);await bp.waitForTimeout(route==='/'?1800:250);if(selector)await bp.locator(selector).first().scrollIntoViewIfNeeded();await screenshot(bp,'before',width,lang,name,route!=='/');}await bp.goto(baseline);await bp.waitForTimeout(1800);await bp.locator('.nav-toggle').click();await bp.waitForTimeout(900);await screenshot(bp,'before',width,lang,'drawer');await bc.close();}
}
for(const js of [false,true]){const c=await context(browser,390,'en',{javaScriptEnabled:js});if(js)await c.route('**/assets/js/site-v3.js',r=>r.abort());const p=await c.newPage();await p.goto(origin+'/expertise');verify(await p.locator('.v3-service-page:visible').count()===3,'Static service descriptions hidden');await p.goto(origin+'/');verify(await p.locator('.v3-study-panel:visible').count()===3,'Static study unreadable');await p.goto(origin+'/approach');verify(await p.locator('.v3-process li:visible').count()===5,'Static process unreadable');await p.locator('#process-0 summary').click();verify(await p.locator('#process-0 details').evaluate(e=>e.open),'Native disclosure fallback failed');passed.push(js?'Blocked V3 script fallback':'No JavaScript fallback');console.log('PASS '+passed.at(-1));await c.close();}
const c=await context(browser,390,'es',{reducedMotion:'reduce'}),p=await c.newPage();await p.goto(origin+'/expertise');await p.locator('#folio-tab-1').click();verify(await p.locator('#service-1').evaluate(e=>getComputedStyle(e).animationName)==='none','Reduced-motion folio animates');await p.locator('[data-emphasis-choice="1"]').click();verify(await p.locator('[data-emphasis-word="1"]').evaluate(e=>getComputedStyle(e).transform)==='none','Reduced-motion emphasis moves');await p.emulateMedia({reducedMotion:'no-preference'});await p.locator('#folio-tab-2').click();verify(await p.locator('#service-2').evaluate(e=>getComputedStyle(e).animationName)==='v3-folio-in','Live preference change ignored');await p.emulateMedia({reducedMotion:'reduce'});await p.goto(origin+'/');await p.locator('[data-study-choice="2"]').click();verify(await p.locator('.v3-study-type em').evaluate(e=>getComputedStyle(e).transform)==='none','Reduced-motion study moves');passed.push('Reduced motion and live preference changes');console.log('PASS '+passed.at(-1));await c.close();
fs.writeFileSync(path.join(output,'browser-results.json'),JSON.stringify({cases:passed.length,assertions,passed,metrics,captures},null,2));console.log(`${passed.length} cases / ${assertions} assertions / ${captures.length} screenshots`);
}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
