/* Controlled Homepage A browser regression. Start tests/review-server.cjs first.
   Chromium by default; EXIF_ENGINE=webkit uses Playwright WebKit (not physical Safari).
   External requests blocked; no real form submissions. */
const {chromium,webkit}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process');
const root=path.resolve(__dirname,'..'),origin=process.env.EXIF_TEST_ORIGIN||'http://127.0.0.1:8080',engine=process.env.EXIF_ENGINE||'chromium';
const out=process.env.EXIF_ARTIFACT_DIR||'/workspace/artifacts/homepage-a/tests';fs.mkdirSync(out,{recursive:true});
let checks=0;const cases=[];function check(value,label){assert(value,label);checks++}
const baseline='b539f86b6f27578170aaa56c0ad42c721d13198b';
function frozen(){const files=cp.execFileSync('git',['ls-tree','-r','--name-only',baseline],{cwd:root,encoding:'utf8'}).trim().split('\n').filter(f=>f.startsWith('assets/')||['expertise.html','approach.html','studio.html','inquire.html','_redirects','_headers'].includes(f));for(const f of files){if(f==='assets/js/editorial-painpoint.js')continue;check(fs.readFileSync(path.join(root,f)).equals(cp.execFileSync('git',['show',baseline+':'+f],{cwd:root})),'Protected file changed: '+f)}const old=cp.execFileSync('git',['show',baseline+':index.html'],{cwd:root,encoding:'utf8'}),now=fs.readFileSync(path.join(root,'index.html'),'utf8');for(const [name,start,end]of [['Dear EXIF','<section class="dear-home"','</main>'],['Navigation','<a class="skip-link"','<main '],['Footer','<footer ','<script src="assets/js/site-config.js"']]){check(old.slice(old.indexOf(start),old.indexOf(end))===now.slice(now.indexOf(start),now.indexOf(end)),name+' markup changed')}const hero=s=>s.slice(s.indexOf('<section class="hero section"'),s.indexOf('<div class="hero-commercial">')>=0?s.indexOf('<div class="hero-commercial">'):s.indexOf('</div></section>'));check(hero(old)===hero(now),'Original hero fallback altered');cases.push('Protected assets, all inner pages, navigation, hero fallback, Dear EXIF and footer byte equality')}
async function context(b,width,lang,reduced=false){const c=await b.newContext({viewport:{width,height:width>=860?900:844},isMobile:width<860,hasTouch:width<860,reducedMotion:reduced?'reduce':'no-preference'});await c.route('https://**/*',r=>r.abort());await c.addInitScript(lang=>localStorage.setItem('exif-language',lang),lang);return c}
async function ready(p){await p.waitForFunction(()=>document.body.classList.contains('exif-header-ready'));await p.waitForTimeout(1400)}
async function touchSwipe(c,p,dx,dy){const s=await c.newCDPSession(p),r=await p.locator('.motion-gallery-viewport').boundingBox(),x=260,y=Math.min(650,r.y+r.height*.5);await s.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y,id:1}]});for(let i=1;i<=10;i++){await s.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x+dx*i/10,y:y+dy*i/10,id:1}]});await p.waitForTimeout(25)}await s.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await p.waitForTimeout(300);await s.detach()}
(async()=>{frozen();const b=await (engine==='webkit'?webkit:chromium).launch(engine==='webkit'?{}:{executablePath:'/usr/bin/chromium',args:['--no-sandbox']});try{
 for(const width of [1440,390,360])for(const lang of ['en','es']){const c=await context(b,width,lang),p=await c.newPage(),errors=[],missing=[];p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.url().startsWith(origin)&&r.status()>=400)missing.push(r.url())});const response=await p.goto(origin);check(response.status()===200,'Homepage loads');await ready(p);check(await p.locator('.exif-loader').count()===0,'Loader releases');check(await p.locator('html').getAttribute('lang')===lang,'Stored language');check(await p.locator('.home-invitation [data-primary-cta]').count()===1,'One hero invitation');const hero=await p.locator('#what-exif-does').boundingBox(),cta=await p.locator('.home-invitation a').boundingBox();check(width>=860?cta.x+cta.width<(await p.locator('.exif-hero-bg').boundingBox()).x:cta.y>=hero.y+hero.height,'CTA respects photographic field');if(width<860)check(Math.abs(hero.height-844)<1,'Original mobile screen height');
 check(await p.locator('.v2-introduction:not(noscript *),.exif-passage,.v3-study,.v2-invitation,.recognition-section').count()===0,'Redundant homepage chapters removed');
 const sequence=await p.locator('main>section').evaluateAll(es=>es.map(e=>e.id));check(JSON.stringify(sequence)===JSON.stringify(['what-exif-does','gap','selected-work','approach','dear-exif']),'A chapter order');
 const title=await p.locator('.exif-hero-copy h1:not([aria-hidden]) .line:last-child .word').evaluate(e=>{const a=document.createRange();a.selectNodeContents(e);const r=a.getBoundingClientRect();return{left:r.left,right:r.right}});check(title.left>=0&&title.right<=width+1,'Hero title fits '+lang);
 await p.locator('.home-choice').evaluate(e=>scrollTo({top:e.getBoundingClientRect().top+scrollY-80,behavior:'instant'}));await p.waitForTimeout(600);const early=await p.locator('.choice-decision strong').evaluate(e=>Number(getComputedStyle(e).opacity));if(engine==='webkit'&&width<860)await p.evaluate(()=>scrollTo({top:scrollY+320,behavior:'instant'}));else await p.mouse.wheel(0,320);await p.waitForFunction(()=>Number(getComputedStyle(document.querySelector('.choice-decision strong')).opacity)>.95);await p.waitForTimeout(200);const late=await p.locator('.choice-decision strong').evaluate(e=>Number(getComputedStyle(e).opacity));check(late>early&&late>.95,'Comparison resolves as native scroll advances');check((await p.locator('[data-copy="question"]').textContent())===(lang==='es'?'¿Por qué tu propiedad?':'Why your property?'),'Bridge localization');check(await p.locator('.home-choice h2,.home-choice strong,.home-choice em').evaluateAll(es=>es.every(e=>{const r=document.createRange();r.selectNodeContents(e);const b=r.getBoundingClientRect();return b.left>=-1&&b.right<=innerWidth+1})),'Bridge copy stays inside viewport');
 await p.locator('.gallery-chapter').scrollIntoViewIfNeeded();await p.waitForTimeout(700);const images=await p.locator('.motion-gallery-item:not([aria-hidden]) img').evaluateAll(es=>es.map(e=>e.getAttribute('src')));check(images.length===13&&images.every((x,i)=>x.includes('exif-gallery-'+String(i+1).padStart(2,'0')+'-')),'13-image original sequence');await p.locator('[data-gallery-pause]').click();await p.waitForTimeout(350);const track=p.locator('.motion-gallery-track'),before=await track.getAttribute('style');await p.waitForTimeout(300);check(await track.getAttribute('style')===before,'Pause stops cruise');await p.locator('[data-gallery-step="next"]').click();await p.waitForTimeout(600);check(await track.getAttribute('style')!==before,'Next works when paused');const next=await track.getAttribute('style');await p.locator('[data-gallery-step="prev"]').click();await p.waitForTimeout(600);check(await track.getAttribute('style')!==next,'Previous works');
 const r=await p.locator('.motion-gallery-viewport').boundingBox(),dragStart=await track.getAttribute('style');await p.mouse.move(r.x+r.width*.7,r.y+r.height*.5);await p.mouse.down();await p.mouse.move(r.x+r.width*.4,r.y+r.height*.5,{steps:12});await p.mouse.up();await p.waitForTimeout(200);check(await track.getAttribute('style')!==dragStart,'Gallery drag works');await p.locator('[data-gallery-pause]').click();check(await p.locator('[data-gallery-pause]').getAttribute('aria-pressed')==='false','Cruise resumes');
 for(const key of ['observe','decide','create']){const card=p.locator('[data-approach="'+key+'"]');await card.click();await p.waitForTimeout(350);check(await card.getAttribute('aria-expanded')==='true','Card '+key+' opens');check(await p.locator('.approach-card[aria-expanded="true"]').count()===1,'Exclusive card selection')}
 await p.locator('#property-url').fill('example.com');await p.locator('.dear-continue').click();check(await p.locator('#property-url').inputValue()==='https://example.com','URL normalizes');await p.locator('[name="message"]').fill('Unsent review draft');await p.locator('[name="name"]').fill('Review');await p.locator('[name="email"]').fill('review@example.com');check(await p.locator('.dear-send').isVisible(),'Dear EXIF expands');check((await p.locator('.dear-continue').innerText())===(lang==='es'?'SEGUIR ESCRIBIENDO':'CONTINUE WRITING'),'Letter localization');
 await p.locator('.nav-toggle').click();await p.waitForTimeout(650);check(await p.locator('main').evaluate(e=>e.inert),'Open drawer protects background');await p.keyboard.press('Escape');await p.waitForTimeout(800);check(!await p.locator('main').evaluate(e=>e.inert),'Drawer releases background');await p.locator('.home-invitation a').click();await p.waitForURL(/inquire(?:\.html)?(?:\?|$)/);check(await p.locator('body').getAttribute('data-page')==='inquire','Native CTA navigates');check(await p.locator('html').getAttribute('lang')===lang,'CTA preserves language');await p.goBack();await ready(p);check(await p.locator('[name="message"]').inputValue()==='Unsent review draft','Letter draft persists');check(!await p.locator('html').evaluate(e=>e.classList.contains('exif-transition-out')),'Back restores transition');check(!errors.length,'No page errors '+errors);check(!missing.length,'No missing local assets '+missing);
 await c.close();cases.push(`${engine} ${width}px ${lang}: loader, hero, cinematic bridge, gallery, cards, letter, CTA, history`);console.log('PASS',cases.at(-1));}
 // All 25 drawer journeys, in both languages and desktop/mobile, including direct entry.
 await Promise.all([1440,390].flatMap(width=>['en','es'].map(async lang=>{const c=await context(b,width,lang,true),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));for(const from of ['home','expertise','approach','studio','inquire'])for(const to of ['home','expertise','approach','studio','inquire']){const response=await p.goto(origin+(from==='home'?'/':'/'+from+'.html'));check(response.status()===200,'Direct entry '+from);await p.waitForTimeout(100);check(await p.locator('body').getAttribute('data-page')===from,'Correct direct page');const toggle=p.locator('.nav-toggle');check(await toggle.evaluate(e=>{const r=e.getBoundingClientRect(),h=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return h===e||e.contains(h)}),'Menu receives hit');if(width===390)await toggle.tap();else await toggle.click();await p.waitForTimeout(150);check(await p.locator('body').evaluate(e=>e.classList.contains('nav-open')),'Drawer opens');const link=p.locator(to==='inquire'?'.v2-nav-inquire':'.v1-nav-link[data-route="'+to+'"]');await link.click();await p.waitForURL(u=>u.pathname===(to==='home'?'/':'/'+to+'.html'));check(await p.locator('body').getAttribute('data-page')===to,'Native route '+from+' → '+to);check(await p.locator('html').getAttribute('lang')===lang,'Journey preserves language');check(!await p.locator('main').evaluate(e=>e.inert),'Destination interactive')}check(!errors.length,'No journey errors');await c.close();cases.push(`${engine} ${width}px ${lang}: 25 native drawer journeys, all five direct pages`);console.log('PASS',cases.at(-1))})));
 const c=await context(b,390,'es',true),p=await c.newPage();await p.goto(origin);await ready(p);await p.locator('.home-choice').scrollIntoViewIfNeeded();check(await p.locator('.choice-decision strong,.choice-decision em').evaluateAll(es=>es.every(e=>getComputedStyle(e).filter==='none'&&Number(getComputedStyle(e).opacity)===1)),'Reduced-motion bridge is immediately readable');await p.locator('.gallery-chapter').scrollIntoViewIfNeeded();await p.waitForTimeout(400);check(await p.locator('[data-gallery-pause]').isDisabled(),'Reduced-motion auto cruise disabled');const track=p.locator('.motion-gallery-track'),before=await track.getAttribute('style');await p.locator('[data-gallery-step="next"]').click();check(await track.getAttribute('style')!==before,'Reduced-motion arrow works');if(engine==='chromium'){const before=await track.getAttribute('style');await touchSwipe(c,p,-130,0);check(await track.getAttribute('style')!==before,'Native horizontal touch moves gallery');await p.locator('.gallery-chapter').scrollIntoViewIfNeeded();const y=await p.evaluate(()=>scrollY);await touchSwipe(c,p,0,-140);check(await p.evaluate(()=>scrollY)>y+40,'Native vertical gallery swipe remains free')}await c.close();cases.push(engine+' reduced motion and gallery input');
 const nojs=await b.newContext({viewport:{width:390,height:844},javaScriptEnabled:false});await nojs.route('https://**/*',r=>r.abort());const np=await nojs.newPage();await np.goto(origin);check(await np.locator('.v2-nojs-nav').isVisible(),'No-JS navigation');check(await np.locator('h1').isVisible(),'No-JS hero');check(await np.locator('.dear-send').isVisible(),'No-JS letter');await nojs.close();cases.push(engine+' no-JS fallback');
 fs.writeFileSync(out+'/'+engine+'-results.json',JSON.stringify({engine,browser:b.version(),checks,cases,passed:true},null,2));console.log('PASS',checks,'checks,',cases.length,'cases');
 }finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
