/* Real pointer/touch navigation across native Pages routing and plain static hosting.
   EXIF_NAV_BEFORE_ROOT optionally enables reproduction of the old canonical loop. */
const {chromium,webkit}=require('playwright'),assert=require('node:assert/strict'),http=require('node:http'),fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process');
const root=path.resolve(__dirname,'..'),output=process.env.EXIF_NAV_ARTIFACT_DIR||path.join(root,'docs/creative/navigation-fix');fs.mkdirSync(output,{recursive:true});
const routes=['home','expertise','approach','studio','inquire'];let checks=0;const results=[];function check(v,m){assert(v,m);checks++}
async function host(dir,mode){const rules=fs.readFileSync(path.join(dir,'_redirects'),'utf8').trim().split('\n').map(l=>l.split(/\s+/));const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.webp':'image/webp','.png':'image/png','.jpg':'image/jpeg','.woff2':'font/woff2'};const s=http.createServer((req,res)=>{const u=new URL(req.url,'http://localhost');let rel=u.pathname;const rule=rules.find(r=>r[0]===rel);if(mode==='pages'){if(rule&&rule[2]!=='200'){res.writeHead(Number(rule[2]),{Location:rule[1]+u.search});return res.end()}if(rule)rel=rule[1];if(rel.endsWith('.html')&&rel!=='/index.html'){res.writeHead(308,{Location:rel.slice(0,-5)+u.search});return res.end()}if(rel==='/'||rel==='/index.html')rel='/index.html';else if(!path.extname(rel))rel+='.html';}else if(rel==='/')rel='/index.html';const f=path.resolve(dir,'.'+rel);if(!f.startsWith(dir+'/')){res.writeHead(403);return res.end()}fs.readFile(f,(e,data)=>{res.writeHead(e?404:200,{'Content-Type':mime[path.extname(f)]||'text/plain'});res.end(e?'Not found':data)})});await new Promise(r=>s.listen(0,'127.0.0.1',r));return {server:s,origin:'http://127.0.0.1:'+s.address().port}}
function preserve(){const baseline='069b827aee17191256dfac4db414356c19fd57fc';function normalize(s){return s.replace(/\/(expertise|approach|studio|inquire)\.html/g,'/$1')}for(const f of ['index.html','expertise.html','approach.html','studio.html','inquire.html','assets/js/site-v1.js']){const old=cp.execFileSync('git',['show',baseline+':'+f],{cwd:root,encoding:'utf8'});check(normalize(fs.readFileSync(path.join(root,f),'utf8'))===normalize(old),'Only navigation URLs change: '+f)}const assets=cp.execFileSync('git',['ls-tree','-r','--name-only',baseline],{cwd:root,encoding:'utf8'}).trim().split('\n').filter(f=>f.startsWith('assets/')&&f!=='assets/js/site-v1.js');for(const f of assets)check(fs.readFileSync(path.join(root,f)).equals(cp.execFileSync('git',['show',baseline+':'+f],{cwd:root})),'Frozen visual/interaction asset '+f);console.log('PASS '+checks+' preservation contracts')}
(async()=>{preserve();if(process.env.EXIF_NAV_PRESERVATION_ONLY==='1')return;for(const engine of ['chromium','webkit']){if(engine==='webkit'&&process.env.EXIF_NAV_SKIP_WEBKIT==='1')continue;const b=await (engine==='chromium'?chromium:webkit).launch(engine==='chromium'?{executablePath:'/usr/bin/chromium',args:['--no-sandbox']}:{});try{
 if(process.env.EXIF_NAV_BEFORE_ROOT){const h=await host(path.resolve(process.env.EXIF_NAV_BEFORE_ROOT),'pages'),c=await b.newContext(),p=await c.newPage();await c.route('https://**/*',r=>r.abort());for(const route of routes.slice(1)){let failed=false;try{await p.goto(h.origin+'/'+route)}catch(e){failed=/redirect/i.test(e.message)}check(failed,engine+' original redirect loop '+route)}await c.close();h.server.close();console.log('PASS '+engine+' original four redirect loops reproduced');}
 for(const mode of ['pages','static'])for(const width of [390,1440]){const h=await host(root,mode),c=await b.newContext({viewport:{width,height:900},hasTouch:width===390,isMobile:width===390});await c.route('https://**/*',r=>r.abort());await c.addInitScript(()=>{sessionStorage.setItem('exif-intro-seen','1')});const p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));
 for(const from of routes){const url=h.origin+(from==='home'?'/':'/'+from+(mode==='static'?'.html':''));const response=await p.goto(url);check(response.status()===200,'Direct page '+from);await p.waitForTimeout(250);check(await p.locator('body').getAttribute('data-page')===from,'Correct direct page');
 for(const to of routes){await p.goto(url);await p.waitForTimeout(200);const toggle=p.locator('.nav-toggle');check(await toggle.evaluate(e=>{const r=e.getBoundingClientRect(),hit=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return hit===e||e.contains(hit)}),'Menu receives native hit');if(width===390)await toggle.tap();else await toggle.click();await p.waitForTimeout(750);check(await p.locator('body').evaluate(e=>e.classList.contains('nav-open')),'Drawer opens');check(await p.locator('.exif-drawer').evaluate(e=>!e.hasAttribute('inert')&&getComputedStyle(e).pointerEvents==='auto'),'Drawer interactive');
 if(from==='expertise'&&to==='studio')await p.screenshot({path:path.join(output,engine+'-'+mode+'-'+width+'-drawer.png')});const link=p.locator(to==='inquire'?'.exif-drawer .v2-nav-inquire':'.exif-drawer .v1-nav-link[data-route="'+to+'"]');await Promise.all([p.waitForNavigation({waitUntil:'domcontentloaded'}),width===390?link.tap():link.click()]);await p.waitForURL(u=>u.pathname===(to==='home'?'/':'/'+to+(mode==='static'?'.html':'')));await p.waitForTimeout(250);check(await p.locator('body').getAttribute('data-page')===to,'Native link arrives '+from+' → '+to);check(!await p.locator('body').evaluate(e=>e.classList.contains('nav-open')),'Destination unlocked');check(!await p.locator('main').evaluate(e=>e.hasAttribute('inert')),'Destination not inert');}
 }
 check(!errors.length,'No JS errors');results.push({engine,mode,width,pairs:25,directPages:5,passed:true,errors});await c.close();h.server.close();console.log('PASS '+engine+' '+mode+' '+width+': all 25 page pairs, native hit/tap, inert, transitions and direct pages');}
 }finally{await b.close()}}fs.writeFileSync(path.join(output,'results.json'),JSON.stringify({checks,results},null,2));console.log(checks+' navigation checks passed')})().catch(e=>{console.error(e);process.exit(1)});
